language: ruby
cache: bundler

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0

script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - dev@rhomobile.com
    on_failure: change
    on_success: never